#!/bin/bash
git pull origin master | egrep --count up-to-date > check
cd games/minetest
git pull origin master
cd ../..
if [[ `cat check` -eq 1 ]]
then
echo "Engine already up-to-date, no need to recompile."
else
cmake . -DRUN_IN_PLACE=1
make -j2
fi
rm check
echo "Minetest updated!"
